---
title: Cody Winton
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
url: http://codywinton.com
tagline: Developer | CEO | Creative
email: cody@codywinton.com
description: 'I''m a multi-stack dev & creative problem-solver. Follow me anywhere
  @codytwinton

'
buttons:
- title: Current Work
  link: http://credntia.com
- title: Contact Me
  link: mailto:cody@codywinton.com
button-1:
  title: Current Work
  link: http://credntia.com
button-2:
  title: Contact Me
  link: mailto:cody@codywinton.com
google_analytics:
  prod_key: UA-103616440-1
  staging_key: testing
social:
  facebook: codytwinton
  twitter: codytwinton
  instagram: codytwinton
  medium: codytwinton
  linked-in: codytwinton
  github: codytwinton
baseurl: 
markdown: kramdown
permalink: pretty
gems:
- jekyll-feed
- jekyll-redirect-from
