---
# Jekyll Settings
title: TrueCoders
timezone: America/Chicago
url: https://truecoders.io
baseurl: 
# Enable once Forestry supports custom collections_dir
# collections_dir: collections
kramdown:
  show_warnings: true
lang: en
liquid:
  error_mode: strict
  strict_filters: true
  # Enable once certain jekyll extensions, like seo, support without errors
  # strict_variables: true
permalink: pretty
remote_theme: codytwinton/portfolio-theme
safe: true
sass:
  style: compressed
strict_front_matter: true

# Jekyll SEO Settings
description: 'Cody Winton: I''m a multi-stack developer & a creative problem solver. Follow me anywhere @codytwinton'
author:
  name: Cody Winton
  picture: "/uploads/profile-image.jpg"
  twitter: codytwinton
email: cody@codywinton.com
image: "/uploads/profile-image.jpg"
logo: "/uploads/profile-image.jpg"
social:
  name: Cody Winton
  links:
  - https://twitter.com/codytwinton
  - https://www.facebook.com/codytwinton
  - https://www.linkedin.com/in/codytwinton
  - https://plus.google.com/+CodyWinton
  - https://github.com/codytwinton
twitter:
  username: codytwinton

# Collections
collections:
  work:
    title: Work
    output: false

# Defaults for Layouts
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: page
- scope:
    path: ''
    type: pages
  values:
    layout: page
