---
title: Cody Winton
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  skills:
    title: Skills
    output: false
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: false
defaults:
- scope:
    path: ''
    type: skills
  values:
    rank: 0
- scope:
    path: ''
    type: work
  values:
    display_title: 
    link: 
    jobs:
    - title: 
      start_date: 
      end_date: 
      body: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
    display_title: 
    is_footer: false
    action_button:
      title: 
      link: 
- scope:
    path: resume.markdown
    type: pages
  values:
    layout: resume
    skills:
    - type: 
      values:
      - title: 
        rank: 0
    experience:
    - start_date: 
      type: 
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
url: http://codywinton.com
email: cody@codywinton.com
description: 'Cody Winton: I''m a multi-stack developer & a creative problem solver.
  Follow me anywhere @codytwinton'
author:
  picture: "/uploads/profile-image.jpg"
  twitter: codytwinton
google_analytics:
  tracking_id: UA-103616440-1
logo: "/uploads/profile-image.jpg"
twitter:
  username: codytwinton
social:
  name: Cody Winton
  links:
  - https://twitter.com/codytwinton
  - https://www.facebook.com/codytwinton
  - https://www.linkedin.com/in/codytwinton
  - https://plus.google.com/+CodyWinton
  - https://github.com/codytwinton
sass:
  style: compressed
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
baseurl: 
markdown: kramdown
permalink: pretty
