---
title: Cody Winton
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: cody@codywinton.com
tagline: Developer | CEO | Creative
description: 'I''m a multi-stack dev & creative problem-solver. Follow me anywhere
  @codytwinton

'
baseurl: 
url: http://codywinton.com
button-1:
  title: Current Work
  link: http://credntia.com
button-2:
  title: Contact Me
  link: mailto:cody@codywinton.com
social:
  facebook: codytwinton
  twitter: codytwinton
  instagram: codytwinton
  medium: codytwinton
  linked-in: codytwinton
  github: codytwinton
markdown: kramdown
gems:
- jekyll-feed
- jekyll-redirect-from
