---
title: Cody Winton
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    display_title: 
    subtitle: 
    action_button:
      title: 
      link: 
    is_footer_page: false
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
url: http://codywinton.com
email: cody@codywinton.com
description: 'Cody Winton: I''m a multi-stack developer & a creative problem solver.
  I''m the CEO at Credntia. Follow me anywhere @codytwinton'
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-sitemap
google_analytics:
  tracking_id: UA-103616440-1
sass:
  sass_dir: styles/
  style: compressed
baseurl: 
markdown: kramdown
permalink: pretty
