---
title: Cody Winton
timezone: America/Chicago
collections:
  authors:
    title: Authors
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    layout: page
    image: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
    subtitle: 
    hero_image: "/uploads/hero.jpg"
    is_header_page: false
    action:
    - title: 
      link: 
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    subtitle: 
    hero_image: "/uploads/hero.jpg"
    author: Cody Winton
    action:
    - title: 
      link: 
url: http://codywinton.com
email: cody@codywinton.com
description: 'Cody Winton: I''m a multi-stack developer & a creative problem solver.
  I''m the CEO at Credntia. Follow me anywhere @codytwinton'
plugins:
- jekyll-feed
- jekyll-redirect-from
google_analytics:
  tracking_id: UA-103616440-1
sass:
  sass_dir: styles/
  style: compressed
baseurl: 
markdown: kramdown
permalink: pretty
