---
title: Cody Winton
timezone: America/Chicago
collections:
  authors:
    title: Authors
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: authors
  values:
    layout: page
    image: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
    subtitle: 
    hero_image: "/uploads/hero.jpg"
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    subtitle: 
    author: 
url: http://codywinton.com
email: cody@codywinton.com
description: 'I''m a multi-stack dev & creative problem-solver. Follow me anywhere
  @codytwinton

'
google_analytics:
  prod_key: UA-103616440-1
  staging_key: testing
social:
  facebook: codytwinton
  twitter: codytwinton
  instagram: codytwinton
  medium: codytwinton
  linked-in: codytwinton
  github: codytwinton
baseurl: 
markdown: kramdown
permalink: pretty
gems:
- jekyll-feed
- jekyll-redirect-from
